import { ProjectItem } from '@/interfaces'

const projects: ProjectItem[] = [
//  {
//     id: 1,
//     name: 'TikTok Analytics',
//     image: '',
//     projectSummary: '',
//     client: '',
//     projectDetails: '',
//     completedDate: '',
//     services: [],

//  },
 {
    id: 2,
    name: 'Polkadot',
    image: 'images/projects/polkadotProj.jpg',
    projectSummary: 'Using LLMs as onboarding and governance tools',
    client: 'Polkadot-Polkassembly',
    projectDetails: './projectDescriptions/polkadot.md',
    completedDate: '',
    services: ['AI'],

 },
 {
    id: 3,
    name: 'Top 3 Global Bank',
    image: 'images/projects/top3GlobalProj.jpg',
    projectSummary: 'Making sense of chaos with AI',
    client: '',
    projectDetails: './projectDescriptions/top3GlobalBank.md',
    services: ['AI', 'Analytics'],
    completedDate: '',
 },
 {
    id: 4,
    name: 'Smart Vaults',
    image: 'images/projects/smartVaultsProj.jpg',
    projectSummary: 'Smart Bitcoin wallet wtih taproot miniscript',
    client: '',
    projectDetails: './projectDescriptions/smartVults.md',
    completedDate: '',
    services: ['Bitcoin'],

 },
 {
    id: 5,
    name: 'Hypha',
    image: 'images/projects/hyphaProj.jpg',
    projectSummary: 'DAO platform for regenerative projects',
    client: 'Hypha',
    projectDetails: './projectDescriptions/hypha.md',
    completedDate: '',
    services: ['VUE', 'DESIGN', 'BLOKCHAIN'],
 },
 {
    id: 6,
    name: 'S&K',
    image: 'images/projects/s&kProj.jpg',
    projectSummary: 'Modern investment due diligence for brokers.',
    client: "Snyder Kearney's",
    projectDetails: './projectDescriptions/s&k.md',
    completedDate: '',
    services: ['Analitycs', 'Banking'],
 },
 {
    id: 7,
    name: 'BennyFi',
    image: 'images/projects/bennyProj.jpg',
    projectSummary: 'Pledge the Yield, not the Principal',
    client: 'BennyFi',
    projectDetails: './projectDescriptions/bennyFi.md',
    completedDate: '',
    services: ['Blockchain', 'Design'],
 },
 {
    id: 8,
    name: 'PRXY',
    image: 'images/projects/prxyProj.jpg',
    projectSummary: 'The best solution for EB-5 compliance',
    client: 'PRXY Co',
    projectDetails: './projectDescriptions/prxy.md',
    completedDate: '',
    services: ['Blockchain', 'Vue'],
 },
 {
    id: 9,
    name: 'Software Solution',
    image: 'images/projects/softwareSolutionProj.jpeg',
    projectSummary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    client: 'Bryan Hennesy',
    projectDetails: './projectDescriptions/lorem.md',
    completedDate: '02/03/2023',
    services: ['Development'],
 },
 {
    id: 10,
    name: 'Digital Marketing',
    image: 'images/projects/digitalMarketingProj.jpeg',
    projectSummary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    client: 'Digital Capita',
    projectDetails: './projectDescriptions/lorem.md',
    completedDate: '08/10/2022',
    services: ['Development'],
 },
 {
    id: 11,
    name: 'Marketing Strategy',
    image: 'images/projects/marketingStrategyProj.jpeg',
    projectSummary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    client: 'Mutil-Digital Capita',
    projectDetails: './projectDescriptions/lorem.md',
    completedDate: '06/06/2022',
    services: ['Development'],
 },
 {
    id: 12,
    name: 'Website Redesign',
    image: 'images/projects/websiteRedesignProj.jpeg',
    projectSummary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    client: 'Will Walters',
    projectDetails: './projectDescriptions/lorem.md',
    completedDate: '10/01/2021',
    services: ['Development'],
 },
 {
    id: 13,
    name: 'Brand Identity',
    image: 'images/projects/brandIdentityProj.jpeg',
    projectSummary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    client: 'Bryan Hennesy',
    projectDetails: './projectDescriptions/lorem.md',
    completedDate: '12/08/2021',
    services: ['Development'],
 },
 {
    id: 14,
    name: 'Development',
    image: 'images/projects/developmentProj.jpeg',
    projectSummary: 'The best solution for EB-5 compliance',
    client: 'Will Walters',
    projectDetails: './projectDescriptions/lorem.md',
    completedDate: '02/26/2023',
    services: ['Blockchain', 'Vue'],
 }
]

export default projects
